name = "mi-proyecto-astro"
type = "javascript"  # Puede ser "javascript" o "webpack" dependiendo de tu configuración

[build]
command = "npm run build"  # O el comando que uses para construir tu proyecto

[env.production]
name = "mi-proyecto-astro-production"

[env.production.vars]
# Aquí puedes definir variables de entorno para el entorno de producción
